DROP TABLE IF EXISTS USERS ;
DROP TABLE IF EXISTS TWEETS ;
DROP TABLE IF EXISTS HEARTS ;
DROP TABLE IF EXISTS ROLES ;
DROP TABLE IF EXISTS USERS_ROLES ;

CREATE TABLE ROLES
(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL UNIQUE,
  PRIMARY KEY (ID)
);

CREATE TABLE USERS
(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  PRIMARY KEY (ID)
);

CREATE TABLE TWEETS
(
  id INT NOT NULL AUTO_INCREMENT,
  content VARCHAR(255) NOT NULL,
  creation_date DATE NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE HEARTS
(
  id INT NOT NULL AUTO_INCREMENT,
  creation_date DATE NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE USER_ROLES
(
  user_id INT NOT NULL,
  role_id INT NOT NULL
);
